runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
# [END handlers]
env_variables:
  CLOUDSQL_CONNECTION_NAME: hacktx-2017:us-central1:free-food
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: averageprogrammers

libraries:
- name: MySQLdb
  version: "latest"
